### PR TITLE
Fixes https://github.com/xelerance/xl2tpd/issues/76

### PR DESCRIPTION
**Pull request by Climax777**
Adds exponential backoff to retransmissions of control packets

### CODE REVIEW

**Comment by Climax777** [comment]
Can anyone test this please?

**Comment by shussain** [comment]
Thank you for your commit. We will be testing your pull request soon.

**Comment by zorun** [comment]
Please don't add a dependency to libm to xl2tpd, unless it is really needed.  On constrained systems such as OpenWRT, this will add too much bloat to the binary.

In this case, using pow() to compute a power of two is completely overkill.  You can simply use binary shifts instead (don't forget to check that the argument is within bounds first).

**Comment by xelerance** [comment]
Quite true, we could do this instead:
````
    m = (int) Math.pow(2, p);
````
replaced with:
````
    m = 1 << p;
````

**Pull request merged**
