### PR TITLE
Pespin/master

### PR DESCRIPTION
**Pull request by pespin**

### CODE REVIEW

**Comment by shussain** [comment]
Thank you for your PR. Things are busy right now but I will review the PR this weekend

**Comment by pespin** [comment]
Thanks. It's basically a bulk of code refactoring to clean the code I did while studying the code for first time. I also fixed some small issues the compiler told me and some nonsense foo I saw.
If these kind of patches are welcome, once current ones are merged I'll be glad to send more cleanup patches and possibly some new features I am looking for (forwarding incoming PPPoE from LAC to LNS).

**Comment by shussain** [comment]
With respect to commit: a09ded852eb38b79f0031ba04bff2266b0e37149, 92ae73b1a9325018b09d2b40cde74d161d4b1e2e, 90ea91dd4a0082a674d6f711a77092c682d96e19 you are right that using bool does make it easier to read. However, you are pulling in an additional library. In the past we have gotten pushback from constrained environment users  about using additional libraries (please see #117)

In commit b8d990e362170ee0236de87d4e08ce288077e75a,   you are using a return at the beginning but the function does more like set flags, sockets, etc. In order to avoid side effects of certain variables being set, I would be hesitant to accept that commit. Perhaps I am missing something and that isn't the case.

---------

I have taken some of your commits and put it in the 1.3.14 dev branch.

**Comment by shussain** [comment]
The following are commits that I have to look more closely at:
a3192126714adf8523b30e783ebf9cc8e453d06d  xl2tpd: start_pppd: Fix truncation of last character
13f98570955abffbad96265b0df2c4a370052621  xl2tpd: Mark internal symbols as static
3b9d4ad22ff6a09699286b5d5ada8808ed155b03  avp: Early failure if no handler to remove indent block 
03731a3deab1143814caad5d211b3592b5a697b5  handle_packet: Rearrange code flow to simplify it

**Comment by pespin** [comment]
> With respect to commit: a09ded852eb38b79f0031ba04bff2266b0e37149, 92ae73b1a9325018b09d2b40cde74d161d4b1e2e, 90ea91dd4a0082a674d6f711a77092c682d96e19 you are right that using bool does make it easier to read. However, you are pulling in an additional library. In the past we have gotten pushback from constrained environment users about using additional libraries (please see #117)

stdbool.h is not a library (no linkage involved), is just a header file with some defines, and it's actually standard in POSIX afaik: https://www.unix.com/man-page/posix/7posix/stdbool.h/

So it should be there for any POSIX compliant system. I don't see any problem in using it regarding the issue you mention.

> 
> In commit b8d990e362170ee0236de87d4e08ce288077e75a, you are using a return at the beginning but the function does more like set flags, sockets, etc. In order to avoid side effects of certain variables being set, I would be hesitant to accept that commit. Perhaps I am missing something and that isn't the case.
> 

I am unable to find that commit in the commit list. Can you share a link to it so I can have a look at it?

> I have taken some of your commits and put it in the 1.3.14 dev branch.

Thanks. I'm happy to comment and fix any issue you see upon review. The quicker they are merged the quicker I may send new changes, since imho the code requires big cleaning/refactoring and so the commits I send mainly seek this objective first of all. I don't want to send many refactoring patches together without review since then it's difficult to rework then if an intermediate path requires modifications.

**Comment by shussain** [comment]
First of, I would like to think you for your commits. You are correct that the code could do with a cleanup. I really appreciate your contributions.

> So it should be there for any POSIX compliant system. I don't see any problem in using it regarding the issue you mention.

Fair enough.

User @zorun do you have any concerns/bojects with using stdbool.h and converting variables to bool as per commit: c3b31c8509762e6d63429161cf470550f25530f4

> > In commit b8d990e362170ee0236de87d4e08ce288077e75a, you are using a return at the beginning but the function does more like set flags, sockets, etc. In order to avoid side effects of certain variables being set, I would be hesitant to accept that commit. Perhaps I am missing something and that isn't the case.
> 
> I am unable to find that commit in the commit list. Can you share a link to it so I can have a look at it?

Sorry I had been using the cherry-pick commit's sha. 

I believe I had been referring to commit 7111dbd43acd92b028c3baa8a14c52a75e119686 but upon re-reading the code, I was mistaken. As such, I have added that commit to 1.314dev branch

In addition, I have reviewed and added all the commits mentioned in my [previous comments](https://github.com/xelerance/xl2tpd/pull/174#issuecomment-471078374)

> The quicker they are merged the quicker I may send new changes, since imho the code requires big cleaning/refactoring and so the commits I send mainly seek this objective first of all. I don't want to send many refactoring patches together without review since then it's difficult to rework then if an intermediate path requires modifications.

I agree. 

As an aside, I did find this PR to be a bit too big. But as you mentioned the code required some refactoring/cleanup and it is likely future changes won't be as big.

**Comment by pespin** [comment]
> As an aside, I did find this PR to be a bit too big. But as you mentioned the code required some refactoring/cleanup and it is likely future changes won't be as big.

Agree, sorry for that, I was simply submitting new (sometimes unrelated) commits as I was reading the code and spotting issues or mangling code so it was more readable.

There's a separate pull request available that fix a specific issue I saw while running a sample setup.

**Comment by shussain** [comment]
Thank you. I will review the PR #175 tomorrow evening

**Comment by shussain** [comment]
I have accepted PR #715 into the 1.3.14dev branch

Most of the commits in this PR are added to 1.3.14dev branch. As such closing this ticket.

**Pull request closed without merging**
